### ISSUE TITLE
Failed to install on Ubuntu

### ISSUE THREAD

**Issue by LuciusMos** [Farama-Foundation/AutoROM#17]
I run ``pip install autorom[accept-rom-license]`` on Ubuntu 18.04.5. Then it shows:

```
  Building wheel for AutoROM.accept-rom-license (pyproject.toml) ... done
  ERROR: Failed building wheel for AutoROM.accept-rom-license
Failed to build AutoROM.accept-rom-license
ERROR: Could not build wheels for AutoROM.accept-rom-license, which is required to install pyproject.toml-based projects
```

However, I have already installed pyproject-toml.

**Comment by benblack769** [comment]
Not sure what is causing this. Is there any other part of this error message, or is this is?

I have just one guess. Is wheel installed?

```
pip install wheel
```
