### ISSUE TITLE
Stuck at Atari ROMs download

### ISSUE THREAD

**Issue by glitchyordis** [Farama-Foundation/AutoROM#24]
System: Ubuntu 20.04
conda virtual env , python=3.8

Hello, I ran the [AutoROM.py](https://github.com/Farama-Foundation/AutoROM/tree/master/src) and I can't seem to proceed from there,the terminal stays at the following line:
"I agree to not distribute these ROMs and wish to proceed: [Y/n]: y"

It would be helpful to know if running AutoROM to get those roms require access to certain websites because my network is monitored. I can then try to request access from my IT department.

Kindly assist me with this. Thank you.

```
python3 AutoROM.py
AutoROM.py:228: UserWarning: ale-py package seems to be empty. Perhaps try reinstalling ale-py.
  warnings.warn(
AutoROM will download the Atari 2600 ROMs.
They will be installed to:
	/home/polaris/anaconda3/envs/py38/lib/python3.8/site-packages/multi_agent_ale_py/roms

Existing ROMs will be overwritten.

I own a license to these Atari 2600 ROMs.
I agree to not distribute these ROMs and wish to proceed: [Y/n]: y
```

**Comment by jjshoots** [comment]
Hi @glitchyordis, thanks for reporting this. For now, could you use autorom v0.4.2? It seems your network may be blocking the torrent link, 0.4.2 downloads the ROMs from a different source which may solve your issue.
