### ISSUE TITLE
0.4.2 still fails to download ROMs

### ISSUE THREAD

**Issue by epignatelli** [Farama-Foundation/AutoROM#34]
Hi there,

I am facing the same issue in #24.

However, installing `0.4.2` does not solve the issue.

```
       File "/tmp/pip-install-ig3zv0fw/autorom-accept-rom-license_b5788b79c9fd43ae826c9bed60314c16/AutoROM.py", line 200, in torrent_tar_to_buffer
          raise RuntimeError("Tried to download ROMs 3 times, which have all failed, please try again or report this issue.")
      RuntimeError: Tried to download ROMs 3 times, which have all failed, please try again or report this issue.
```

Note the `0.4.2` still refers to `AutorROM.accept-rom-license-0.5.4.tar.gz`:
```
ip install autorom[accept-rom-license]==0.4.2 --no-cache-dir
Collecting autorom[accept-rom-license]==0.4.2
  Downloading AutoROM-0.4.2-py3-none-any.whl (16 kB)
Collecting AutoROM.accept-rom-license
  Downloading AutoROM.accept-rom-license-0.5.4.tar.gz (12 kB)
```

**Comment by qgallouedec** [comment]
`pip install AutoROM.accept-rom-license==0.4.2` should do he trick. 

@maintainers, any update about this bug?

**Comment by lcebaman** [comment]
> > `pip install AutoROM.accept-rom-license==0.4.2` should do he trick.
> > @maintainers, any update about this bug?
> 
> You made my day!
This won't work when it is a dependency for other packages.

**Comment by epignatelli** [comment]
Can you be more specific?

_requirements.txt
```
numpy
AutoROM.accept-rom-license==0.4.2
```

`pip install -r requirements.txt` works for me

**Comment by qgallouedec** [comment]
Any update on this?

**Comment by jjshoots** [comment]
Hi everyone, we've recently taken the feedback from everyone and made a new release for AutoROM. In this release, you're able to bypass the requirement for torrenting if you already have the pre-torrented tar available. This should solve all™ of the issues at hand. To use the new release:

1. Download the tar.gz file from [here](https://drive.google.com/file/d/1uuPaYGf2f4DaEUJkS36LvSEWokgC8qjI/view?usp=share_link).
2. Ensure that AutoROM is up to the latest version `pip3 install autorom>=0.5.5`.
3. Install the roms using the pre-installed tar.gz file `AutoROM --accept-license --source-file path/to/Roms.tar.gz`.

Disclaimer: The Roms.tar.gz are currently hosted on a personal GDrive account. For legal reasons these cannot be hosted on the main github repo. As such, availability of the Roms via GDrive is not guaranteed.
