### ISSUE TITLE
`pip install autorom[accept-rom-license]` fails on zsh

### ISSUE THREAD

**Issue by epignatelli** [Farama-Foundation/AutoROM#35]
`pip install autorom[accept-rom-license]` returns    
`zsh: no matches found: autorom[accept-rom-license]`

Workaround:
`pip install "autorom[accept-rom-license]"`

It does work on bash.

**Comment by pseudo-rnd-thoughts** [comment]
Thank you, we will update our tutorials

**Comment by epignatelli** [comment]
Or.. avoid using dashed in the optional build name?
