### ISSUE TITLE
Problems with torrenting ROMs due to network

### ISSUE THREAD

**Issue by jjshoots** [Farama-Foundation/AutoROM#39]
Hi everyone, we've recently taken the feedback from everyone and made a new release (0.5.5) for AutoROM. In this release, you're able to bypass the requirement for torrenting if you already have the pre-torrented tar available. This should solve all™ of the issues at hand. To use the new release:

1. Download the tar.gz file from [here](https://drive.google.com/file/d/1uuPaYGf2f4DaEUJkS36LvSEWokgC8qjI/view?usp=share_link).
2. Ensure that AutoROM is up to the latest version `pip3 install autorom>=0.5.5`.
3. Install the roms using the pre-installed tar.gz file `AutoROM --accept-license --source-file path/to/Roms.tar.gz`.

Disclaimer: The Roms.tar.gz are currently hosted on a personal GDrive account. For legal reasons these cannot be hosted on the main github repo. As such, availability of the Roms via GDrive is not guaranteed.

**Comment by xbdeng** [comment]
I can not download the tar.gz file, so what should I do?

**Comment by jjshoots** [comment]
@xbdeng Updating to AutoROM v0.6.0 should fix this issue:
```
pip3 install autorom>=0.6.0 -U
```
